package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"

	"github.com/theorigamicorporation/toc-whmcs-mcp/internal/registry"
)

// emit renders the generated registry source.
//
// Output must be deterministic: CI compares a fresh generation against the
// committed file, so any ordering that depends on map iteration or scrape
// completion order would produce a spurious diff. Actions are sorted by
// category then name; parameters keep their documented order, which is
// meaningful to a reader.
func emit(actions []registry.Action) ([]byte, error) {
	sorted := make([]registry.Action, len(actions))
	copy(sorted, actions)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Category != sorted[j].Category {
			return sorted[i].Category < sorted[j].Category
		}
		return sorted[i].Name < sorted[j].Name
	})

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/docgen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Source: https://developers.whmcs.com/api/api-index/\n")
	b.WriteString("// Regenerate with: just gen\n")
	b.WriteString("//\n")
	b.WriteString("// Safety classification is NOT generated. It lives in classification.go\n")
	b.WriteString("// and is maintained by hand, because the vendor documentation does not say\n")
	b.WriteString("// whether an action reads or destroys.\n\n")
	b.WriteString("package registry\n\n")
	fmt.Fprintf(&b, "// GeneratedActionCount is the number of actions scraped from the vendor\n")
	fmt.Fprintf(&b, "// documentation at generation time.\n")
	fmt.Fprintf(&b, "const GeneratedActionCount = %d\n\n", len(sorted))
	b.WriteString("var generatedActions = []Action{\n")

	for _, a := range sorted {
		b.WriteString("\t{\n")
		fmt.Fprintf(&b, "\t\tName:     %s,\n", quote(a.Name))
		fmt.Fprintf(&b, "\t\tCategory: %s,\n", quote(a.Category))
		fmt.Fprintf(&b, "\t\tSlug:     %s,\n", quote(a.Slug))
		fmt.Fprintf(&b, "\t\tSummary:  %s,\n", quote(a.Summary))
		writeParams(&b, "Params", a.Params)
		writeParams(&b, "Response", a.Response)
		b.WriteString("\t},\n")
	}

	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w", err)
	}
	return src, nil
}

func writeParams(b *bytes.Buffer, field string, params []registry.Param) {
	if len(params) == 0 {
		return
	}
	fmt.Fprintf(b, "\t\t%s: []Param{\n", field)
	for _, p := range params {
		fmt.Fprintf(b, "\t\t\t{Name: %s, Type: %s", quote(p.Name), typeConst(p.Type))
		if p.Required {
			b.WriteString(", Required: true")
		}
		if p.Deprecated {
			b.WriteString(", Deprecated: true")
		}
		if p.Description != "" {
			fmt.Fprintf(b, ", Description: %s", quote(p.Description))
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t\t},\n")
}

func typeConst(t registry.ParamType) string {
	switch t {
	case registry.TypeInt:
		return "TypeInt"
	case registry.TypeFloat:
		return "TypeFloat"
	case registry.TypeBool:
		return "TypeBool"
	case registry.TypeArray:
		return "TypeArray"
	case registry.TypeObject:
		return "TypeObject"
	default:
		return "TypeString"
	}
}

func quote(s string) string { return strconv.Quote(s) }
